// Fill in  your WiFi networks SSID and password
#define SECRET_SSID "AllowEverything"
#define SECRET_PASS "WKDGNSDL!12"

// Fill in the hostname of your AWS IoT broker
#define SECRET_BROKER "avg618qij0qji-ats.iot.ap-northeast-2.amazonaws.com"

// Fill in the boards public certificate
const char SECRET_CERTIFICATE[] = R"(
-----BEGIN CERTIFICATE-----
MIICxTCCAa2gAwIBAgIVANO2X3hikbhp5WpLoenyXHNlc/bSMA0GCSqGSIb3DQEB
CwUAME0xSzBJBgNVBAsMQkFtYXpvbiBXZWIgU2VydmljZXMgTz1BbWF6b24uY29t
IEluYy4gTD1TZWF0dGxlIFNUPVdhc2hpbmd0b24gQz1VUzAeFw0yMjExMjIxMzM5
MjNaFw00OTEyMzEyMzU5NTlaMFQxCjAIBgNVBAYTAVkxCjAIBgNVBAgTAVkxCjAI
BgNVBAcTAVkxCjAIBgNVBAoTAVkxCjAIBgNVBAsTAVkxFjAUBgNVBAMTDU15TUtS
V2lGaTEwMTAwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASh66CggXvVbShoKvqr
Lr+CrOmKrJuOGCY+SzFcZoZj3exT52unTqQeM3XXt/gqi0Ad/Zk4Na9Z1wZywJBG
MHrio2AwXjAfBgNVHSMEGDAWgBTypy0v7Zo8+/HKFTnk2AM+n+ty8jAdBgNVHQ4E
FgQUNqxIcrTshRJsjTa3YveO2RD6KjowDAYDVR0TAQH/BAIwADAOBgNVHQ8BAf8E
BAMCB4AwDQYJKoZIhvcNAQELBQADggEBAFk6TEZ6L8XI9KisK1giOQorzz2MOC5J
kmvN2HQP3yWrJUw9HOK9RRYI1M/puJVVtIxGHDDqYOongZxK6DLbJwRsjCEZbjmi
l1/aSV1DFuvST8GSeEJGf4UnsoiMiQzE22/8sUgQMrql0aWx5W5URmsAttcF+YW7
MA+A/JqJ6cO8mSohgit/m5+8w4YlXrn6PHp7n25vSQfHy1n5x5FBPxEpVwgd0T49
kmqOnsp4lKfw+V2IRKboqgTxZYwqq8as3HkuPM9pT1mY9TKHRa2mKWzq7XLTOrk6
ANRrNyjplcpOEnt1UsGX45olAdaBqxsdorsTbZQjg+75SK+dHAyMGjU=
-----END CERTIFICATE-----
)";